---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name rustfs
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        RUSTFS_ACCESS_KEY: "{{ .username }}"
        RUSTFS_SECRET_KEY: "{{ .password }}"
        RUSTFS_IDENTITY_OPENID_CLIENT_ID: "{{ .RUSTFS_OPENID_CLIENT_ID }}"
        RUSTFS_IDENTITY_OPENID_CLIENT_SECRET: "{{ .RUSTFS_OPENID_CLIENT_SECRET }}"
  dataFrom:
  - extract:
      key: minio
