---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-config-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: gluetun-config-secret
    creationPolicy: Owner
    template:
      data:
        custom.conf: |
          [Interface]
          PrivateKey = {{ .wg_private_key }}
          Address = {{ .wg_address }}
          DNS = 127.0.0.2
          MTU = 1320

          [Peer]
          PublicKey = {{ .wg_public_key}}
          PresharedKey = {{ .wg_preshared_key }}
          AllowedIPs = {{ .wg_allowed_ips }}
          Endpoint = {{ .wg_endpoint }}
          PersistentKeepalive = 15

  dataFrom:
    - extract:
        key: gluetun
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gluetun-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .wg_private_key }}"
        WIREGUARD_PRESHARED_KEY: "{{ .wg_preshared_key }}"
        WIREGUARD_ADDRESSES: "{{ .wg_address }}"
        FIREWALL_VPN_INPUT_PORTS: "51457"
        OPENVPN_USER: "{{ .openvpn_user }}"
        OPENVPN_PASSWORD: "{{ .openvpn_password }}"
        SERVER_COUNTRIES: "United States"
  dataFrom:
  - extract:
      key: gluetun
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name2 qbittorrent-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name2
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .api_key }}"
  dataFrom:
  - extract:
      key: qbittorrent
