---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-config-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: gluetun-config-secret
    creationPolicy: Owner
    template:
      data:
        custom.conf: |
          [Interface]
          # Bouncing = 0
          # NetShield = 0
          Moderate NAT = on
          NAT-PMP (Port Forwarding) = on
          VPN Accelerator = on
          PrivateKey = {{ .wg_private_key }}
          Address = 10.2.0.2/32
          DNS = 10.2.0.1

          [Peer]
          PublicKey = {{ .wg_public_key}}
          AllowedIPs = 0.0.0.0/0
          Endpoint = {{ .wg_endpoint }}
  dataFrom:
    - extract:
        key: gluetun
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gluetun-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        OPENVPN_USER: "{{ .vpn_user }}"
  dataFrom:
  - extract:
      key: gluetun
---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name2 qbittorrent-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name2
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        GLUETUN_CONTROL_SERVER_API_KEY: "{{ .api_key }}"
  dataFrom:
  - extract:
      key: qbittorrent
