---
originRequest:
  originServerName: "external.${SECRET_DOMAIN}"

ingress:
  - hostname: "${SECRET_DOMAIN}"
    service: https://envoy-external.network.svc.cluster.local:443
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://envoy-external.network.svc.cluster.local:443
  - hostname: "analogpuddle.com"
    service: https://envoy-external-ap.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.analogpuddle.com"
  - hostname: "*.analogpuddle.com"
    service: https://envoy-external-ap.network.svc.cluster.local:443
    originRequest:
      originServerName: "external.analogpuddle.com"
  - service: http_status:404
