---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name searxng-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      data:
        SEARXNG_SECRET: "{{ .SEARXNG_SECRET_KEY }}"
  dataFrom:
  - extract:
      key: searxng
