---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: coral-tpu
spec:
  rules:
    - name: coral.tpu
      labels:
        feature.node.kubernetes.io/coral-tpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0880"] }
            vendor: { op: In, value: ["1ac1"] }
            device: { op: In, value: ["089a"] }
