# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bitmagnet
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      bitmagnet:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/tparker00/postgres-init
              tag: 16.8@sha256:e36b10229bb317004bc9de7f9c3ca592da04c2c197084223480a148c7927398b
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: bitmagnet-secret
        containers:
          main:
            image:
              repository: ghcr.io/bitmagnet-io/bitmagnet
              tag: v0.10.0
            args:
            - worker
            - run
            - --all
            env:
              TZ: ${TIMEZONE}
            envFrom: *envFrom
            resources:
              requests:
                cpu: 10m
                memory: 256Mi
          gluetun:
            dependsOn: main
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0
            env:
              VPN_SERVICE_PROVIDER: protonvpn
              VPN_PORT_FORWARDING: "on"
              DOT: "off"
              FIREWALL_INPUT_PORTS: 3333
              FIREWALL_VPN_INPUT_PORTS: 3334
              FIREWALL_OUTBOUND_SUBNETS: 10.51.0.0/16,10.50.0.0/16,10.10.5.0/24,18.0.0.0/8"
              DNS_KEEP_NAMESERVER: "on"
            envFrom:
              - secretRef:
                  name: gluetun-secret
            securityContext:
              runAsUser: 0
              allowPrivilegeEscalation: true
              capabilities:
                add:
                  - NET_ADMIN
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        controller: *app
        primary: true
        ports:
          http:
            port: 3333
    serviceMonitor:
      main:
        enabled: true
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 20s
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/name: Bitmagnet
          gethomepage.dev/icon: bitmagnet.png
        hosts:
        - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              identifier: main
              port: http
        tls:
        - hosts:
          - *host
