---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldns-technitium-watchdog
  namespace: network
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: externaldns-technitium-watchdog
  namespace: network
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: externaldns-technitium-watchdog
  namespace: network
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: externaldns-technitium-watchdog
subjects:
  - kind: ServiceAccount
    name: externaldns-technitium-watchdog
    namespace: network
