---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: talos-backup
spec:
  interval: 12h

  maxHistory: 2
  chart:
    spec:
      chart: talos-backup
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: sergelogvinov
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    priorityClassName: system-cluster-critical
    env:
      - name: CLUSTER_NAME
        value: "${CLUSTER_NAME}"
    envFrom:
        - secretRef:
            name: talos-secret

  valuesFrom:
    - kind: Secret
      name: talos-backup-helm-values
