---
# yaml-language-server: $schema=https://schemas.ajgon.casa/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-status-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: github-status-token-secret
    template:
      data:
        token: "{{ .GITHUB_STATUS_TOKEN }}"
  dataFrom:
    - extract:
        key: github-status-token
