# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app node-exporter-probes
  namespace: flux-system
spec:
  targetNamespace: observability
  dependsOn:
    - name: kube-prometheus-stack
  path: ./kubernetes/apps/observability/exporters/node-exporter/probes
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
