apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:rgiRr9Iwh8n8UdwhXn8gCGNs1o8eHqNDh0J9Mba0XZWl5EorQW6yUQ==,iv:gekRz5gY1c8vYeT68YH13WLjvDlhcQarmlw7M6YfQhs=,tag:Tw84s8SqcRDzQCdvYrG1Sg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBualUrT09ucmxmN1FwZnZQ
            UDlCRVhPQ0RIZkE2bUxScU1SK254UkdXOUhzCkpraWJNT05vQ3hxQkFkWDdYejZv
            VWcrdVdMdzhqZElkUEI4MW00bW0rTEkKLS0tIDZiV1VWaDFwL2c0ZXZ1TjgxdnFM
            NGM4UC9Jbnl1eGd1VWdIZVFmVzJjdTQKtj+V2xpMF0BiCPe0KO/mv592pFpVjM4g
            eDGBrY0HQBQoim2DbLkPQtCtYL/I89ZuHL6cuI127IviSW6uHEaBig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T21:27:28Z"
    mac: ENC[AES256_GCM,data:nDd8QyH6m4F0ZdNCcXOJ6oOP61mpVwq9nl3XVWkksQo3LVvxMmJAczkLGO57VaMCFxOlp7V+dkbUe3Dn1bkILq17PbWNMqlIqV2MRSwgbU8+0FSmPcdMOy5rBVRgaGaBmwJuw+Pbbcm0p1IKekIuCYMIHcOpZl0T7yflN4cyGyA=,iv:pY009HHD+/uW/yTYwn8Lbh9y/iF5WOeU6v+SQPtic88=,tag:bj4cAgHg4PVH3SfD+8+x2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
