apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:0jSHAYPnENLpFG+eu4QnE1IzIxTyupKcxAGFC4kpv1cNJtxmMfFQkw==,iv:jXfbiQ/IqSkVWjsx1PLE1KqbPWTxcvDcTWnzK9cs2DI=,tag:ZanmmiyAjyaMsAYwuVus8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbkpJM2M4dnVwQXVGY2xn
            bGtCVVpCVW1GdG5uWDNjUWRLM1ZzVVA2QkdnCmxyZUJ0WDR6V01mUUJLNWNuOUl2
            Nk40V214UDh3UlhtN2EyTG14TE5OdzAKLS0tIGlqaDlQQzgwNC8wL0R3cGZlZzFh
            TUhuMnVqazRCZks0K2FCM0FhdWdIK3MKK0uujVYg/RKaMMjZjBiIzsQtqn4LFl5e
            Jjfy8puAL8vkNuHC1pKRdk+s9bOmg6vFkRdizTi2BD4/9fudxJWNDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:25:25Z"
    mac: ENC[AES256_GCM,data:LhNY6EHgkklJgksB80UW5a1spiG6Y0rAM7pfc/kY72Nycnhgd0wmsOY9O2YMb2czjNvKBMpTv7s66w3ZJplLigppRD+3c+AtA4QoaZdJcaw1Te9OnJQDVHEK89br0IsUBT4g6R8zPE3OV7aYpd1GgB5aGrXgzZhqNm2jwI1otGQ=,iv:z8gmacadny8fdP5+7g0PWjIcOF4YmmJex55YN9N2DFQ=,tag:JVCn3f0JpUgkdsmszXdXig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
