---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name immich-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .jwt_token }}"
        IMMICH_WEB_URL: http://immich-web.media:3000
        IMMICH_SERVER_URL: http://immich-server.media:3001
        PUBLIC_IMMICH_SERVER_URL: https://photos.${SECRET_DOMAIN}
        # REDIS
        REDIS_HOSTNAME: "dragonfly.database.svc.cluster.local"
        REDIS_PORT: "6379"
        # DATABASE
        DB_HOSTNAME: &dbHost postgres-rw.database.svc.cluster.local
        DB_USERNAME: &dbUser "{{ .pg_user }}"
        DB_PASSWORD: &dbPass "{{ .pg_pass }}"
        DB_DATABASE_NAME: &dbName immich
        DB_PORT: "5432"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pg_pass }}"
  dataFrom:
  - extract:
      key: immich
  - extract:
      key: cloudnative-pg
