# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: barman-cloud
spec:
  chart:
    spec:
      chart: barman-cloud
      sourceRef:
        kind: HelmRepository
        name: barman-cloud
  interval: 1h
  # No values here :(
