---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vymanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn: []
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      vymanager:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/tparker00/postgres-init
              tag: 16.12@sha256:d3141d1cdb69529a6d8f60af96253278fa5a0223944fdb36f609821e79bc291d
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: vymanager-secret
        containers:
          frontend:
            image:
              repository: ghcr.io/community-vyprojects/vymanager-frontend
              tag: beta@sha256:ec2af3c6be862fe9cd4db60ad38b882dc3c597b2b6e7ae71f2149b2c25a9e49c
            env:
              TZ: ${TIMEZONE}
              NODE_ENV: production
              VYMANAGER_ENV: production
              BETTER_AUTH_URL: "https://vymanager.${SECRET_DOMAIN}"
              NEXT_PUBLIC_APP_URL: "https://vymanager.${SECRET_DOMAIN}"
              NEXT_PUBLIC_API_URL: "https://api-vymanager.${SECRET_DOMAIN}"
            envFrom: *envFrom
          backend:
            image:
              repository: ghcr.io/community-vyprojects/vymanager-backend
              tag: beta@sha256:097616909b39a877e168d820cdcf8ce281c44f03da813731d3170e9b0afc01bc
            env:
              TZ: ${TIMEZONE}
              FRONTEND_URL: "https://vymanager.${SECRET_DOMAIN}"
            envFrom: *envFrom
    service:
      main:
        controller: *app
        primary: true
        ports:
          http:
            port: &frontend_port 3000
      api:
        controller: *app
        ports:
          http:
            port: &backend_port 8000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - name: vymanager-main
                port: *frontend_port
        parentRefs:
          - name: envoy-internal
            namespace: network
      api:
        hostnames: ["api-{{ .Release.Name }}.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - name: vymanager-api
                port: *backend_port
        parentRefs:
          - name: envoy-internal
            namespace: network
