---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vymanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  dependsOn: []
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      vymanager:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/tparker00/postgres-init
              tag: 16.14@sha256:2640eff9680517194edfd6a92f22fb1321b3b10fdf5f672d774be02dc0486065
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: vymanager-secret
        containers:
          frontend:
            image:
              repository: ghcr.io/community-vyprojects/vymanager-frontend
              tag: beta@sha256:76dfd750c3001d97cb6434303023a7fb3c8dcbf30ded90513961b9ae6d2ae3f6
            env:
              TZ: ${TIMEZONE}
              NODE_ENV: production
              VYMANAGER_ENV: production
              BETTER_AUTH_URL: "https://vymanager.${SECRET_DOMAIN}"
              NEXT_PUBLIC_APP_URL: "https://vymanager.${SECRET_DOMAIN}"
              NEXT_PUBLIC_API_URL: "https://api-vymanager.${SECRET_DOMAIN}"
            envFrom: *envFrom
          backend:
            image:
              repository: ghcr.io/community-vyprojects/vymanager-backend
              tag: beta@sha256:3dd0b8fd5425da09ed684d6a43ec11d94b5671fa3b8ef218ec4d3791e8e1bf87
            env:
              TZ: ${TIMEZONE}
              FRONTEND_URL: "https://vymanager.${SECRET_DOMAIN}"
            envFrom: *envFrom
    service:
      main:
        controller: *app
        primary: true
        ports:
          http:
            port: &frontend_port 3000
      api:
        controller: *app
        ports:
          http:
            port: &backend_port 8000
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - name: vymanager-main
                port: *frontend_port
        parentRefs:
          - name: envoy-internal
            namespace: network
      api:
        hostnames: ["api-{{ .Release.Name }}.${SECRET_DOMAIN}"]
        rules:
          - backendRefs:
              - name: vymanager-api
                port: *backend_port
        parentRefs:
          - name: envoy-internal
            namespace: network
      analogpuddle:
        hostnames: ["{{ .Release.Name }}.analogpuddle.com"]
        rules:
          - backendRefs:
              - name: vymanager-main
                port: *frontend_port
        parentRefs:
          - name: envoy-internal-ap
            namespace: network
      analogpuddle-api:
        hostnames: ["api-{{ .Release.Name }}.analogpuddle.com"]
        rules:
          - backendRefs:
              - name: vymanager-api
                port: *backend_port
        parentRefs:
          - name: envoy-internal-ap
            namespace: network
