---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name unpackerr-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        UN_LIDARR_0_API_KEY: "{{ .lidarr_token }}"
        UN_RADARR_0_PATHS_0: "{{ .radarr_token }}"
        UN_READARR_0_API_KEY: "{{ .readarr_token }}"
        UN_SONARR_0_API_KEY: "{{ .sonarr_token }}"
  dataFrom:
  - extract:
      key:  lidarr
  - extract:
      key:  radarr
  - extract:
      key:  readarr
  - extract:
      key:  sonarr
