---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  K8S_CLUSTER_CIDR: 10.68.0.0/16
  K8S_POD_CIDR: 10.68.0.0/16
  K8S_SERVICE_CIDR: 10.86.0.0/16
  CILIUM_BGP_SVC_RANGE: 10.10.2.0/24
  CLUSTER_NAME: shore
