---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tun-device
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      tun-device:
        type: daemonset
        pod:
          automountServiceAccountToken: false
          enableServiceLinks: false
          hostNetwork: true
          hostPID: true
          nodeSelector:
            kubernetes.io/os: "linux"
        containers:
          app:
            image:
              repository: ghcr.io/squat/generic-device-plugin
              tag: 6475ff5d0927c0f25b3a39a661aa657ca190d0ef
            args:
              - --device
              - |
                name: tun
                groups:
                  - count: 1000
                    paths:
                      - path: /dev/net/tun
            securityContext:
              privileged: true
            resources:
              requests:
                cpu: 50m
                memory: 10Mi
              limits:
                memory: 20Mi
    persistence:
      device-plugin:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
        hostPathType: Directory
        globalMounts:
          - path: /var/lib/kubelet/device-plugins
            readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        hostPathType: Directory
        globalMounts:
          - path: /dev
            readOnly: true
