---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app syncthing
  namespace: flux-system
spec:
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/storage/syncthing/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: syncthing-config
      MFS_CAPACITY: 2Gi
      APP2: syncthing-data
      MFS2_CAPACITY: 50Gi
      MFS2_ACCESSMODES: ReadWriteOnce
