---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: smartctl-exporter
spec:
  type: oci
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
