apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nvidia-gpu-operator
  namespace: flux-system
spec:
  targetNamespace: gpu-operator
  path: ./kubernetes/apps/gpu/operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  timeout: 5m
