apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WNnk3c5abRQ3XHy6RVSoS7vsP+CDOPZD,iv:t+kg6Tzdd5uvtSq2QjyNpnTEmZ6+0poUCfEbVOgu8Lc=,tag:7qspLkuqfSq8/zMsXun80Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb1J6RWp0UFJSUEszdFB6
            dHF2d0N6RnAycmF4SlVaekF3RU5YTktTYkdFCmxINnBIcGl3WHlrR296Q1FjM3My
            QVM3OVNWRmFFenAwT09sMzNsd0xjSHMKLS0tIEJ4NEFqRS8yZFdWWmRhdGhkbmJp
            NmZob3llNFBwdXJNOTczbGgxbVJBVk0KI9O4QjGHJ1PAyvmw96UevL2c4GfRuFOR
            7WEu4Z9aWR+1A/+l7TRHOKjdnjAfrSGI/zqmw3hT/26XWf5O575JWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T19:10:52Z"
    mac: ENC[AES256_GCM,data:1Wszvnx6mveZWNAjdTM887ZDu7idg5vZumLBQgwQO+dqQRUDuA6r0qKcurtz6mCTCZdyC5SE1Pt/ELphjRe3XLh7mksIh84MreEutvJLXk4/b5HKymLU9iYQZTqLROqvMC/w1EVtVH/OIg5vXn/QgTAJpG72K7arwcTcO2z6yvU=,iv:9exDy3UXrPyYjARXLw9UetDl5aJtAFP/go/5oGgiVmQ=,tag:5V0snhPaFWJliYwqIJO5/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
