apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:vc2QQlsrr1H9XpqlyWxsugf2IBKF/Y1s,iv:uQPH6Y4WoV10yGBCN07a8RZkAT0lFeczyjbEvlf71Ig=,tag:JON+OcD7u60jhJamMJXiXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL2t0OTVsVmxOSmVVdUhp
            clp4WFlFQ29ocDMvRmxFYk9OYjV5WkZhc2k0CllzWFpHeDdDWHJEVEZudCtEekd1
            VXZ1ditxWVZ2Q1RUbTJWamp0M2FqUmMKLS0tIElEbEtRWnl6blpPcHJEenJKNzAx
            NHZrMml2eWg5cTFiK2NKRjNrUnRpSFEKTxbX9osplEzUd2JxYqxxh18sSRYtsXYV
            cdpJM/QaXThQJo3lwYmw4ejO0KR7VnL2zlkrfL3Q/dLpomLmp5aWDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:25:25Z"
    mac: ENC[AES256_GCM,data:VTodKk8UnLZdlcvkkoLcZjHU10B5MytjDEnmD2kMtrMwUXMPMfOIbDkXP1iAnWjrkbu/leCrIl9gJU2nMXguYZFG9AmcfxCaZlHUVDgHW48SOV5PUb+KnPWSZk6FYWqLGTc2NUyBiUCoOpOQNUR1Jwu7mcyduxbVHe9dQBD1JPw=,iv:yRCgDWygnTGsjS6ZTLOIPkJ0apHmw5EheqzpPx6EpgM=,tag:knQIC6UaCWMSJIuByCNVkg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
