---
# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json
sonarr:
  sonarr:
    base_url: http://sonarr.downloads.svc.cluster.local:8989
    api_key: !env_var SONARR__API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    # Templates from https://github.com/recyclarr/config-templates
    include:
      # Quality definitions
      - template: sonarr-quality-definition-series
      - template: sonarr-quality-definition-anime
      # WEB-1080p
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p
      # WEB-2160p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
      # Remux-1080p - Anime
      - template: sonarr-v4-quality-profile-anime
      - template: sonarr-v4-custom-formats-anime

    quality_profiles:
      - name: WEB-1080p
      - name: WEB-2160p

    custom_formats:
      # Optional
      - trash_ids:
          # Unwanted
          - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
          - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
          - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
          - 06d66ab109d4d2eddb2794d21526d140 # Retags
          - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        assign_scores_to:
          - name: WEB-1080p
          - name: WEB-2160p

      # Block DV, boost HDR10+
      - trash_ids:
          - 9b27ab6498ec0f31a3353992e19434ca # DV (WEBDL)
          - 0dad0a507451acddd754fe6dc3a7f5e7 # HDR10+ Boost
          - 385e9e8581d33133c3961bdcdeffb7b4 # DV HDR10+ Boost
        assign_scores_to:
          - name: WEB-2160p
      # Block SDR except SDR WEB
      - trash_ids:
          - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p
      # Anime
      - trash_ids:
          - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored
          - b2550eb333d27b75833e25b8c2557b38 # 10bit
          - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
        assign_scores_to:
          - name: Remux-1080p - Anime
            score: 0

radarr:
  radarr:
    base_url: http://radarr.downloads.svc.cluster.local
    api_key: !env_var RADARR__API_KEY
    delete_old_custom_formats: true
    replace_existing_custom_formats: true
    include:
      - template: radarr-quality-definition-movie
      # HD Bluray + WEB
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web
      # UHD Bluray + WEB
      - template: radarr-quality-profile-uhd-bluray-web
      - template: radarr-custom-formats-uhd-bluray-web
    custom_formats:
      # Optional
      - trash_ids:
          # Unwanted
          - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
          - 90cedc1fea7ea5d11298bebd3d1d3223 # EVO (no WEBDL)
          - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
          - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
          - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
          - f537cf427b64c38c8e36298f657e4828 # Scene
        assign_scores_to:
          - name: HD Bluray + WEB
          - name: UHD Bluray + WEB
      # Block DV, boost HDR10+
      - trash_ids:
          - 923b6abef9b17f937fab56cfcf89e1f1 # DV (WEBDL)
          - b17886cb4158d9fea189859409975758 # HDR10+ Boost
          - 55a5b50cb416dea5a50c4955896217ab # DV HDR10+ Boost
        assign_scores_to:
          - name: UHD Bluray + WEB
      # UHD Audio (to enable with decent audio setup)
      # - trash_ids:
      #     - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
      #     - 2f22d89048b01681dde8afe203bf2e95 # DTS X
      #     - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
      #     - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
      #     - 3cafb66171b47f226146a0770576870f # TrueHD
      #     - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
      #     - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
      #     - e7c2fcae07cbada050a0af3357491d7b # PCM
      #     - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
      #     - 185f1dd7264c4562b9022d963ac37424 # DD+
      #     - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
      #     - 1c1a4c5e823891c75bc50380a6866f73 # DTS
      #     - 240770601cc226190c367ef59aba7463 # AAC
      #     - c2998bd0d90ed5621d8df281e839436e # DD
      #   assign_scores_to:
      #     - name: UHD Bluray + WEB
      #     - name: FR-MULTi-VO-UHD
      # Block SDR except SDR WEB
      - trash_ids:
          - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: UHD Bluray + WEB
