---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/refs/heads/main/config/crd/bases/postgresql.cnpg.io_clusters.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  annotations:
    # required for seamless bootstrap: https://github.com/cloudnative-pg/cloudnative-pg/issues/5778#issuecomment-2783417464
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  instances: 3
  # Immich v2.3.1 requires VectorChord >=0.3 <0.6
  # renovate: datasource=docker depName=ghcr.io/tensorchord/cloudnative-vectorchord versioning=loose enabled=false
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.14-1.1.1@sha256:4a26ca6aad2482289f4a3d3317ccbf1439ce3de140994598375a1f4c4e2e9f8d
  primaryUpdateStrategy: unsupervised

  storage:
    size: 15Gi
    storageClass: openebs-hostpath

  enableSuperuserAccess: true
  superuserSecret:
    name: cloudnative-pg-secret

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "500"
      shared_buffers: 512MB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  # https://github.com/cloudnative-pg/cloudnative-pg/issues/2570
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "4Gi"

  monitoring:
    enablePodMonitor: true

  backup:
    retentionPolicy: 60d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath:  s3://immich/
      endpointURL: https://s3.${SECRET_DOMAIN}
      # Note: serverName version needs to be incremented or changed
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster immich-v1
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key

  bootstrap:
    recovery:
      source: &previousCluster immich-v1
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster

  #   initdb:
  #     database: immich
  #     owner: immich
  #     secret:
  #       name: immich-pg-secret
  #     import:
  #       type: microservice
  #       databases:
  #         - immich
  #       source:
  #         externalCluster: postgres
  #     postInitApplicationSQL:
  #              - CREATE EXTENSION IF NOT EXISTS vchord CASCADE
  #              - CREATE EXTENSION IF NOT EXISTS vector CASCADE
  #              - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE
  # externalClusters:
  #   - name: postgres
  #     connectionParameters:
  #       host: postgres-lb.database.svc
  #       port: "5432"
  #       user: immich
  #       dbname: immich
  #     password:
  #       name: immich-pg-secret
  #       key: password
