---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/refs/heads/main/config/crd/bases/postgresql.cnpg.io_scheduledbackups.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-daily
spec:
  backupOwnerReference: self
  cluster:
    name: immich
  schedule: "@daily"
  immediate: true
