---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/core.v1.namespace.json
apiVersion: v1
kind: Namespace
metadata:
  name: system-upgrade
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
