apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:iILNzb8a3Zge+vosXW6w+7+bSdomgK7kYWo2/vz+efh0ZcGAp/ii1A==,iv:fiO6488/z8R6CHGB9r/8d88WwxXeihsz6rF4eI/11zo=,tag:a1FWYllZbcL1uVGovtRRcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbFkzbXlTUUwrK3RVc1lF
            TDljR0FQZFE5L0VNNXZvM3lSLzY1TFNTMFUwCkVSRWwzQzNpc0Fyc2dwL2RocnN6
            TG1NNEVyWUZRdzFWQTA1Rk1QLzJpZ3MKLS0tIFY2alNhcDhDckNoYm12ZzRLVHNM
            S05qUXlTL3RKckZidGcxVDhwRGN3ZUUK1EGM0+CFqWhdi0CvjefzO5kfcWGJ2mNp
            yFioK9lkup+yk9sauTOmu+Z8VPIChOsswa9YMaCFKMswyaacm7Opig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T15:18:10Z"
    mac: ENC[AES256_GCM,data:cB8e0F8Xc911j4jLf7xcbZ1ULDNAaJqCD4QJ67Qa7Uoa0lSHXI6lUfcR49x+Q5GpS9U/KA3z7jn/F9+AotIOxa3NhbI6V9HP4JpWS6t7dlF+qz3OBpip0NryYW+vnmES7fh4wi5Bltlx+0m9o16+KHDYNdwsZxBhX4q/hIsc7UA=,iv:bKADrPfdgquOP0acACOtK3F7WH40Ro5a/v9Lx/AHe0o=,tag:r168y6KHfSDKeLPNr/CuRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
