apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:TDMQmzdAbNGH0ogaVZxh/08O5lUbHa/z/jTBMLjnnMiqju141NLZZg==,iv:ZCJ1HpiRobHFjk6xg+/ZEv+uWI++dHvwtJREKZhVD/c=,tag:6FpEZZu3B94+Re1zxiMLTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVE56d21kb1l2Si9raVJG
            MUNVajh6dm9LaG1UNE95NFloMzVPc1UzQ2dJCnUvZkd3NGxCd0duZkR2b1ErMm4x
            M0hSK216dVRJaXFJeXFJZ0Z6QWdxbkkKLS0tIHJETHk5ZFRrRlBaYmJjNHRmRVBQ
            emFsM3NmSW1nRzZiV3VRQUFtWnVsS2MKZZRfgX8kXdKccTLHG+P3BXqoY6WawbBB
            qOtyomkY4/dmDv4ZIp5AKrxcCZMXvyxc6F68YLGrPFAM3EcByAElIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T19:10:52Z"
    mac: ENC[AES256_GCM,data:q5BQWt5gmPlCy9H/o3i8XKVf9EPNoqdpZ1DGhJRhr7YBY9aRJ6eX5SjUlVZhWAJMjKCdBojlMqVotR1idOa/CEhKXX7NmLWi6pOtWnm/xf3haaaPbYUES2kbncPU4XYQJ8UTq2Nkl9bRBSIJANSV4DI1UDxsrYTD288gWSr40Aw=,iv:UTMxLUA54W5UOQVHvmlIfLAv//wy8IkEn/VVGVs2s5U=,tag:9eWXlL6EDDdkj3RMPOG7+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
