apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:FpAJXdOXjxX6Q+AKnGKNzBLjg41ypF1ykg34VO3U7gdApPzKvy92RA==,iv:y3yNmNVjlAbwsWRkJRYHVxN/ulHhmcT+PoLYS10F0S4=,tag:zIMeOtQO84lEDEqxSA8Oug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r2gl2pd3gmys7u9jnt5ueth8rrj7u9k5rkzqmmcmq52qe09jffuq5n2l5m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNmkrdFJ0T1VRR2N4K3hi
            clFFOC9HWmpYMTluLzlyaDllN3pYK2dwUkdFCkRIV3R3R1ZEcUp0TERBWVNya25p
            TmxJNENUZmhsVEhDSEgrSWZaY3A0bUkKLS0tIE5oTkZDazBxYk9tNWsrdHBDNGVw
            endyWitrek5qOEhqdkEyQkdad3V3MzQKTQuFs1JWtSKMXrVYUx82mRnsn39YieE+
            2NNS12V4yq4fDP1b4OngAtd7DjT/wcxK2Y6TFqmI7ibnz60Kpz99mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T22:25:25Z"
    mac: ENC[AES256_GCM,data:U/lq5tfbyHH3MG76RXzPewm0QflIqvXD4L71xUPKKK3fAibIzu0fodJhGASM/cjFrFx4p2h2CNz6FEtDoYURmvf4wzmDIhOzdOCI7b2p+JJ1cvy7k1ZfqdT4jQglMeFlY8eCrQien5d+M15UbIGjmHW4Lu8juZw7jeUb8/ddBiQ=,iv:J2O0SsICo/Hm4/BqgzZKw45X62/ejAAEQQVzaQlSfmo=,tag:7zLm46gvU2zQcv2qZO3H5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
